spring:
  application:
    name: clinicafiap-controle-requisicoes
  cloud:
    gateway:
      mvc:
        routes:
          - id: CONSULTAS_SERVICE
            uri: lb://CONSULTAS_SERVICE
            #uri: http://localhost:8082
            predicates:  
              - Path=/consultas/**
            filters:
              - RewritePath=/consultas/(?<segment>.*), /${segment}
          - id: USUARIOS_SERVICE
            uri: lb://USUARIOS_SERVICE
            #uri: http://localhost:8085
            predicates: 
              - Path=/usuarios/**
            filters:
              - RewritePath=/usuarios/(?<segment>.*), /${segment}
server:
  port: 8083
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost